const brandsData = [
    {
        id: 1,
        name: 'Patagonia',
        description: 'Outdoor clothing and gear company committed to environmental sustainability',
        sustainability_rating: 5,
        is_sustainable: true,
        eco_certifications: 'B Corp, Fair Trade Certified, 1% for the Planet',
        sustainability_details: 'Uses recycled materials, offers clothing repair services, donates 1% of sales to environmental causes, transparent supply chain',
        website_url: 'https://www.patagonia.com',
        country: 'United States',
        region: 'North America'
    },
    {
        id: 2,
        name: 'Allbirds',
        description: 'Sustainable footwear company using natural materials',
        sustainability_rating: 4,
        is_sustainable: true,
        eco_certifications: 'B Corp, Carbon Neutral Certified',
        sustainability_details: 'Uses renewable materials like merino wool and tree fiber, carbon-neutral shipping, transparent carbon footprint labeling',
        website_url: 'https://www.allbirds.com',
        country: 'United States',
        region: 'North America'
    },
    {
        id: 3,
        name: 'Tentree',
        description: 'Apparel company that plants 10 trees for every item purchased',
        sustainability_rating: 5,
        is_sustainable: true,
        eco_certifications: 'B Corp, Climate Neutral Certified',
        sustainability_details: 'Plants 10 trees per item, uses sustainable materials like hemp and recycled polyester, ethical manufacturing',
        website_url: 'https://www.tentree.com',
        country: 'Canada',
        region: 'North America'
    },
    {
        id: 4,
        name: 'Lush',
        description: 'Fresh handmade cosmetics company',
        sustainability_rating: 4,
        is_sustainable: true,
        eco_certifications: 'Living Wage Employer, Ethical Buying',
        sustainability_details: 'Minimal packaging, fresh ingredients, ethical sourcing, against animal testing',
        website_url: 'https://www.lush.com',
        country: 'United Kingdom',
        region: 'Europe'
    },
    {
        id: 5,
        name: 'Max Fashion',
        description: 'Value fashion brand offering affordable clothing and accessories',
        sustainability_rating: 2.5,
        is_sustainable: false,
        eco_certifications: 'None publicly listed',
        sustainability_details: 'Runs clothing donation and upcycling drives, partners with NGOs, limited transparency in sourcing and environmental reporting',
        website_url: 'https://www.maxfashion.in',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 6,
        name: 'Westside',
        description: 'Mid-premium fashion and lifestyle brand owned by Tata Trent',
        sustainability_rating: 3.5,
        is_sustainable: true,
        eco_certifications: 'Reports under BRSR (Tata Group sustainability framework)',
        sustainability_details: 'Resource efficiency initiatives, plastic recovery program, improved packaging, sustainability reporting through Trent Group',
        website_url: 'https://www.westside.com',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 7,
        name: 'Zudio',
        description: 'Affordable fast-fashion brand targeting mass market consumers',
        sustainability_rating: 2,
        is_sustainable: false,
        eco_certifications: 'None independent; covered under Trent Group reporting',
        sustainability_details: 'High-turnover fast-fashion model, limited sustainability transparency, some waste reduction initiatives like reusable fabric bags',
        website_url: 'https://www.zudio.com',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 8,
        name: 'Reliance Trends',
        description: 'Mass-market fashion brand under Reliance Retail',
        sustainability_rating: 3,
        is_sustainable: false,
        eco_certifications: 'Pro Earth line claims, Reliance sustainability reporting',
        sustainability_details: 'Some sustainable product lines and recycled materials, supply-chain initiatives via Reliance sustainability goals, limited brand-specific transparency',
        website_url: 'https://www.relianceretail.com/trends.html',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 9,
        name: 'Pantaloons',
        description: 'Value and fast-fashion brand under Aditya Birla Fashion & Retail',
        sustainability_rating: 3.5,
        is_sustainable: true,
        eco_certifications: 'ABFRL sustainability framework, Better Cotton initiatives',
        sustainability_details: 'Targets for zero waste to landfill, sustainable packaging, increasing share of products with sustainable attributes',
        website_url: 'https://www.pantaloons.com',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 10,
        name: 'Fabindia',
        description: 'Ethical lifestyle and apparel brand focused on traditional crafts',
        sustainability_rating: 4,
        is_sustainable: true,
        eco_certifications: 'Craft-based and natural materials focus, social enterprise model',
        sustainability_details: 'Supports artisan communities, uses natural materials, low-impact production practices, strong social sustainability emphasis',
        website_url: 'https://www.fabindia.com',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 11,
        name: 'House of Anita Dongre',
        description: 'Fashion house including AND, Global Desi, and Grassroot',
        sustainability_rating: 4,
        is_sustainable: true,
        eco_certifications: 'Plastic recycling partnerships, ethical production claims',
        sustainability_details: 'Grassroot label emphasizes handcraft and sustainable materials, recycling programs, artisan livelihood support',
        website_url: 'https://www.anitadongre.com',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 12,
        name: 'No Nasties',
        description: 'Ethical clothing brand focused on sustainability and transparency',
        sustainability_rating: 5,
        is_sustainable: true,
        eco_certifications: 'Fair Trade Certified, Organic Cotton, Vegan, Carbon Negative',
        sustainability_details: '100% organic materials, fair trade, carbon-negative operations, transparent impact reporting, tree planting programs',
        website_url: 'https://www.nonasties.in',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 13,
        name: 'Doodlage',
        description: 'Upcycled and recycled fashion label focused on zero waste',
        sustainability_rating: 4.5,
        is_sustainable: true,
        eco_certifications: 'Upcycling-focused, ethical production claims',
        sustainability_details: 'Uses factory waste and recycled fabrics, fair wage production, seasonless and zero-waste design model',
        website_url: 'https://doodlage.in',
        country: 'India',
        region: 'Asia'
    },
    {
        id: 14,
        name: 'Okhai',
        description: 'Social enterprise fashion brand supporting rural artisans',
        sustainability_rating: 4.5,
        is_sustainable: true,
        eco_certifications: 'Artisan empowerment programs, community-based production',
        sustainability_details: 'Handcrafted apparel, supports rural women artisans, promotes sustainable livelihoods and traditional crafts',
        website_url: 'https://okhai.org',
        country: 'India',
        region: 'Asia'
    },
    {
    id: 15,
    name: 'Gini & Jony',
    description: 'Indian kidswear fashion brand offering apparel for children across India',
    sustainability_rating: null,
    is_sustainable: null,
    eco_certifications: 'Not publicly listed',
    sustainability_details: 'Large kidswear chain; limited publicised sustainability initiatives or environmental/social disclosures',
    website_url: 'https://www.giniandjony.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 16,
    name: 'Cottonworld',
    description: 'Indian lifestyle clothing brand specialising in natural-fabric apparel (cotton, linen) for men and women',
    sustainability_rating: 3.5,
    is_sustainable: true,
    eco_certifications: 'Commitment to organic cotton and recycled materials in select lines',
    sustainability_details: 'Focuses on natural fabrics, aims to use more recycled materials, supports cotton farmer communities; more transparency than mass brands',
    website_url: 'https://cottonworld.net/',
    country: 'India',
    region: 'Asia'
},
{
    id: 17,
    name: 'Louis Philippe',
    description: 'Premium Indian menswear brand under Aditya Birla Fashion & Retail',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently listed at brand level',
    sustainability_details: 'Premium men’s fashion brand with high volumes; sustainability driven mostly by ABFRL group initiatives rather than brand-specific programs',
    website_url: 'https://www.louisphilippe.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 18,
    name: 'Aza Fashions',
    description: 'Luxury multi-designer retail fashion brand in India',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Not prominently publicised',
    sustainability_details: 'Focuses on luxury design and multi-designer curation; craftsmanship-driven but limited explicit sustainability certifications',
    website_url: 'https://www.azafashions.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 19,
    name: 'Oxemberg',
    description: 'Indian menswear brand for formal and casual apparel under Siyaram group',
    sustainability_rating: 2,
    is_sustainable: false,
    eco_certifications: 'None publicly listed',
    sustainability_details: 'Large scale menswear brand with conventional production and minimal public sustainability communication',
    website_url: 'https://www.oxemberg.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 20,
    name: 'Biba',
    description: 'Women’s ethnic fashion brand offering kurtas, suits and fusionwear',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None publicly listed',
    sustainability_details: 'Large-scale production, limited sustainability communication, some use of natural fabrics but no transparent reporting or certifications',
    website_url: 'https://www.biba.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 21,
    name: 'W for Women',
    description: 'Women’s ethnic and fusion fashion brand under TCNS Clothing',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'TCNS sustainability reporting claims',
    sustainability_details: 'Introduced limited eco-friendly collections, improving packaging practices, but lacks transparent supply chain disclosures',
    website_url: 'https://www.wforwoman.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 22,
    name: 'Manyavar',
    description: 'Premium Indian ethnic menswear brand known for wedding and festive clothing',
    sustainability_rating: 2,
    is_sustainable: false,
    eco_certifications: 'None publicly listed',
    sustainability_details: 'High production volume, focus on embellishment-heavy garments, minimal sustainability reporting or eco initiatives',
    website_url: 'https://www.manyavar.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 23,
    name: 'Aurelia',
    description: 'Women’s ethnic brand under TCNS Clothing focusing on affordable fashion',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'TCNS sustainability reporting',
    sustainability_details: 'Limited eco initiatives, basic packaging improvements, low transparency in sourcing and production practices',
    website_url: 'https://www.shopforaurelia.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 24,
    name: 'Roadster',
    description: 'Casualwear brand owned by Myntra, focused on denim and everyday wear',
    sustainability_rating: 3.5,
    is_sustainable: true,
    eco_certifications: 'Sustainable denim initiatives, recycled cotton claims',
    sustainability_details: 'Introduced “Roadster Sustain” line using more sustainable denim processes, recycled fabrics, and eco-friendly trims',
    website_url: 'https://www.myntra.com/roadster',
    country: 'India',
    region: 'Asia'
},
{
    id: 25,
    name: 'HRX',
    description: 'Athleisure and lifestyle brand co-owned by Hrithik Roshan and Myntra',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently disclosed',
    sustainability_details: 'Limited sustainability messaging, some recycled polyester products, focus remains on performance and branding',
    website_url: 'https://www.myntra.com/hrx',
    country: 'India',
    region: 'Asia'
},
{
    id: 26,
    name: 'Bewakoof',
    description: 'Youth-focused casualwear and streetwear D2C brand',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Claims of sustainable fabrics in select collections',
    sustainability_details: 'Introduced recycled cotton products and eco packaging efforts but lacks verified certifications and full transparency',
    website_url: 'https://www.bewakoof.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 27,
    name: 'Campus Sutra',
    description: 'Youth casual fashion brand offering affordable trend-driven apparel',
    sustainability_rating: 2,
    is_sustainable: false,
    eco_certifications: 'None publicly listed',
    sustainability_details: 'Fast-fashion model with limited sustainability initiatives or transparency in supply chain practices',
    website_url: 'https://www.campussutra.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 28,
    name: 'Nicobar',
    description: 'Premium lifestyle and apparel brand focused on contemporary Indian design',
    sustainability_rating: 4,
    is_sustainable: true,
    eco_certifications: 'Sustainable materials claims',
    sustainability_details: 'Focuses on natural fabrics, longevity of design, responsible production, and eco-conscious packaging',
    website_url: 'https://www.nicobar.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 29,
    name: 'Bhane',
    description: 'Contemporary Indian fashion brand with minimalist aesthetics',
    sustainability_rating: 4,
    is_sustainable: true,
    eco_certifications: 'Sustainable fabric sourcing claims',
    sustainability_details: 'Uses natural fabrics, small-batch production, ethical manufacturing narratives, transparency-focused branding',
    website_url: 'https://www.bhane.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 30,
    name: 'Van Heusen',
    description: 'Premium menswear and formalwear brand under Aditya Birla Fashion & Retail',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Covered by ABFRL sustainability commitments',
    sustainability_details: 'Corporate-level sustainability initiatives on energy, water, and materials via ABFRL, but limited brand-specific sustainability storytelling',
    website_url: 'https://www.vanheusenindia.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 31,
    name: 'Allen Solly',
    description: 'Casual and semi-formal fashion brand, part of Aditya Birla Fashion & Retail',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Covered by ABFRL sustainability framework',
    sustainability_details: 'Known for smart-casual apparel; some sustainable capsule collections, but overall fast-fashion leaning with group-level ESG initiatives',
    website_url: 'https://www.allensolly.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 32,
    name: 'Peter England',
    description: 'Mass-market menswear brand for formal and casual wear under ABFRL',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'ABFRL ESG reporting',
    sustainability_details: 'High-volume mid-range menswear focused on accessibility, with limited organic or recycled product focus at visible brand level',
    website_url: 'https://www.peterengland.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 33,
    name: 'Raymond',
    description: 'Legacy Indian menswear and textiles brand known for suiting and formalwear',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Group-level environmental and social initiatives',
    sustainability_details: 'Runs initiatives on water and energy in textile mills and has some eco-fabric lines; still largely conventional textile-heavy production',
    website_url: 'https://www.raymond.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 34,
    name: 'Park Avenue',
    description: 'Premium menswear brand from Raymond Group',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'Covered under Raymond Group initiatives',
    sustainability_details: 'Premium formal and semi-formal focus, with limited explicit sustainability communication beyond group textile initiatives',
    website_url: 'https://www.raymond.in/park-avenue',
    country: 'India',
    region: 'Asia'
},
{
    id: 35,
    name: 'Indian Terrain',
    description: 'Menswear brand focused on smart casuals and outdoor-inspired clothing',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Select organic cotton and better-cotton sourcing',
    sustainability_details: 'Offers some eco-focused lines and promotes long-lasting wardrobe staples; disclosure remains lighter than pure-play sustainable brands',
    website_url: 'https://www.indianterrain.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 36,
    name: 'Flying Machine',
    description: 'Indian denim and youth fashion brand under Arvind Fashions',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Arvind Group denim sustainability programs',
    sustainability_details: 'Backed by Arvind’s lower-water and lower-chemical denim processes; brand itself does limited consumer-facing sustainability communication',
    website_url: 'https://www.flyingmachine.co.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 37,
    name: 'Mufti',
    description: 'Casual and denimwear brand targeted at young men',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Trend-led denim and streetwear focus with limited published data on sustainable materials or supply-chain practices',
    website_url: 'https://www.muftijeans.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 38,
    name: 'Spykar',
    description: 'Indian denim-heavy youth fashion brand',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Focus on fashion denim; may use modern wash techniques, but does not strongly highlight third-party sustainability certifications',
    website_url: 'https://www.spykar.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 39,
    name: 'Killer',
    description: 'Denim and casualwear brand under Kewal Kiran Clothing',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Mass-market denim brand with conventional production and limited sustainability messaging',
    website_url: 'https://www.killerjeans.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 40,
    name: 'Wrogn',
    description: 'Celebrity-led youth fashion label co-founded with Virat Kohli',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Streetwear-driven brand; has experimented with some eco fabrics but does not focus on sustainability as a core narrative',
    website_url: 'https://www.wrogn.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 41,
    name: 'Yousta',
    description: 'Youth-focused, ultra-affordable fashion brand by Reliance Retail',
    sustainability_rating: 2,
    is_sustainable: false,
    eco_certifications: 'Reliance group-level ESG initiatives',
    sustainability_details: 'Fast-fashion oriented concept targeting Gen Z with very low price points; limited visible sustainability disclosures',
    website_url: 'https://www.yousta.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 42,
    name: 'Lifestyle Stores',
    description: 'Department-store style fashion and lifestyle retailer with multiple in-house brands',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Landmark Group sustainability initiatives',
    sustainability_details: 'Drives group-level initiatives in energy, waste, and packaging; each in-house fashion brand has limited public ESG detail',
    website_url: 'https://www.lifestylestores.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 43,
    name: 'Shoppers Stop',
    description: 'Large fashion and lifestyle department store chain in India',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'Corporate ESG and CSR disclosures',
    sustainability_details: 'Publishes efforts on energy, waste, and social programs; carries many third-party brands with varied sustainability profiles',
    website_url: 'https://www.shoppersstop.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 44,
    name: 'FabAlley',
    description: 'Online-first women’s fashion brand with trend-driven collections',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Some conscious collections and slow-fashion messaging, but majority of range is conventional fast fashion',
    website_url: 'https://www.faballey.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 45,
    name: 'Indya',
    description: 'Modern ethnic-fusion womenswear brand from the House of Indya',
    sustainability_rating: 3,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Offers modular, mix-and-match occasionwear; some attempts to promote rewear but does not anchor brand on sustainability',
    website_url: 'https://www.houseofindya.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 46,
    name: 'Global Desi',
    description: 'Boho-chic ethnic fusion brand under House of Anita Dongre',
    sustainability_rating: 3.5,
    is_sustainable: true,
    eco_certifications: 'Backed by Anita Dongre group sustainability initiatives',
    sustainability_details: 'Part of a group that invests in artisan livelihoods and waste reduction; more trend-focused but supported by a strong sustainability ethos',
    website_url: 'https://www.globaldesi.in',
    country: 'India',
    region: 'Asia'
},
{
    id: 47,
    name: 'AND',
    description: 'Contemporary westernwear brand for women under House of Anita Dongre',
    sustainability_rating: 3.5,
    is_sustainable: true,
    eco_certifications: 'Anita Dongre sustainability and ethical production programs',
    sustainability_details: 'Modern silhouettes with improved material sourcing, backed by the group’s ethical production and sustainability-driven initiatives',
    website_url: 'https://www.andindia.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 48,
    name: 'Pothys',
    description: 'South Indian retail chain specialising in silk sarees and ethnicwear',
    sustainability_rating: 2.5,
    is_sustainable: false,
    eco_certifications: 'None prominently listed',
    sustainability_details: 'Supports traditional weaving communities through demand for handloom and silk, but lacks modern sustainability reporting or certifications',
    website_url: 'https://www.pothys.com',
    country: 'India',
    region: 'Asia'
},
{
    id: 49,
    name: 'Nalli',
    description: 'Heritage saree brand known for Kanjivaram and handloom silks',
    sustainability_rating: 3.5,
    is_sustainable: true,
    eco_certifications: 'Traditional handloom focus',
    sustainability_details: 'Promotes durable, long-lasting handloom sarees and supports traditional artisans; lower-impact per wear though limited formal ESG reporting',
    website_url: 'https://www.nalli.com',
    country: 'India',
    region: 'Asia'
}
];

module.exports = brandsData;